### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by MajorWaffles** [HyperFlareMC/PMRequisites#1]
You should add 
/gmc 
/gma 
/gms 
/gmsp 
And last 
/realname
To find out the player thats nicknamed real name.

**Comment by HyperFlareMC** [comment]
Hmm. With the /gmc, and such, I don't see this as necessary. You can go into your pocketmine.yml file and add those commands as aliases for their respective gamemode. If I unregistered the default gamemode commands and added those, there would be quite a bit of confusion.

As far as the realname command goes, it may be hard because they could be using special characters that not everyone has. Anything else?

**Comment by HyperFlareMC** [comment]
Closing
